server.port: 8001
server.error.include-message: always

spring.application.name: product

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

spring.data.mongodb:
  auto-index-creation: true
  host: localhost
  port: 27017
  database: product-db

spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings.input:
    destination: products
    group: productsGroup
    consumer:
      maxAttempts: 3
      backOffInitialInterval: 500
      backOffMaxInterval: 1000
      backOffMultiplier: 2.0

  rabbit:
    bindings.input.consumer:
      autoBindDlq: true
      republishToDlq: true

  kafka:
    binder:
      brokers: 127.0.0.1
      defaultBrokerPort: 9092
    bindings.input.consumer:
      enableDlq: true

spring.rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: guest

logging:
  level.root: INFO
  com.mj: DEBUG
  org.springframework.data.mongodb.core.MongoTemplate: DEBUG

management.endpoint.health.show-details: "always"
management.endpoints.web.exposure.include: "*"
---
spring.config.activate.on-profile: docker

server.port: 8080

eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/

spring.data.mongodb.host: mongodb

spring.rabbitmq.host: rabbitmq
spring.cloud.stream.kafka.binder.brokers: kafka