server.port: 8003
server.error.include-message: always

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

spring.datasource:
  url: jdbc:mysql://localhost:3307/review-db
  username: user
  password: pwd
  driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
    initialization-fail-timeout: 10000

spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings.input:
    destination: reviews
    group: reviewsGroup
    consumer:
      maxAttempts: 3
      backOffInitialInterval: 500
      backOffMaxInterval: 1000
      backOffMultiplier: 2.0

  rabbit:
    bindings:
      input:
        consumer:
          autoBindDlq: true
          republishToDlq: true

  kafka:
    binder:
      brokers: 127.0.0.1
      defaultBrokerPort: 9092
    bindings:
      input:
        consumer:
          enableDlq: true

spring.rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: guest

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
---
spring.config.activate.on-profile: docker

server.port: 8080

spring.datasource:
  url: jdbc:mysql://mysql:3306/review-db

spring.rabbitmq.host: rabbitmq

spring.cloud.stream.kafka.binder.brokers: kafka